### ISSUE TITLE
HTML is nicely structured/organized

### ISSUE THREAD

**Issue by ad3429** [geckopaddles/prj-rev-bwfs-tea-cozy#1]
https://github.com/geckopaddles/prj-rev-bwfs-tea-cozy/blob/master/teacozy/index.html#L8-L103

Your HTML is very nicely organized/structured, and you followed excellent code practices such as indenting, readability, commenting, etc. Make sure to keep up the good work!

**Comment by geckopaddles** [comment]
Thanks!
