### ISSUE TITLE
CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [geckopaddles/prj-rev-bwfs-tea-cozy#2]
https://github.com/geckopaddles/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/style.css#L11-L102

Your CSS is short, clean and succinct -- good job! Your styling also matches the styling of the specification, so you did an excellent job of following these directions. Keep it up!

**Comment by geckopaddles** [comment]
Thanks!
